#!/bin/bash
set -e

# Setup Host with container prerequisite
apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

# Add docker engine package repository
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

# !! The following command points to stable !!
add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

# install docker engine (community edition)
apt-get update && apt-get install -y docker-ce
