#!/bin/bash
set -e

# Setup systemd launch command + docker daemon config
mkdir -p /etc/docker /etc/systemd/system/docker.service.d

# Drop-in docker.service config override
cat <<\EOF >/etc/systemd/system/docker.service.d/daemon.conf
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd --config-file=/etc/docker/daemon.json
EOF
