version: "3"

services:
  redis-1:
    container_name: redis-1
    image: redis:3
    logging:
      driver: awslogs
      options:
        awslogs-region: ${aws_region}
        awslogs-group: ${aws_log_group}
        tag: "{{ .Name }}"
    volumes:
      - data:/data
    networks:
      - default

networks:
  default:
    external:
      name: ${network}

volumes:
  data:
    external:
      name: ${redis_data_vol}
